project:
  type: website

website:
  title: "ospo-survey-website"
  navbar:
    background: primary
    title: false
    logo: images/logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: status.qmd
        text: Updates
  page-footer:
    background: primary
    left: "Built with [Quarto](https://quarto.org)"
    center: "Copyright 2025, Regents of the University of California"
    right:
      - icon: github
        href: https://github.com/UC-OSPO-Network/ospo-survey-website
        target: _blank

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true

