project:
  type: website

website:
  title: "ospo-survey-website"
  favicon: images/logo.svg
  navbar:
    title: false
    logo: images/logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: status.qmd
        text: Updates
  page-footer:
    left: "Built with [Quarto](https://quarto.org)"
    center: "Copyright 2025 Regents of the University of California"
    right:
      - icon: github
        href: https://github.com/UC-OSPO-Network/ospo-survey-website
        target: _blank
      - icon: envelope
        href: mailto:ospo@library.ucsb.edu
      - text: |
        <a href="https://ucospo.net" target="_blank"><img src="images/logo.svg" class="custom-icon"></a>

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true

