project:
  type: website

website:
  title: "ospo-survey-website"
  navbar:
    title: false
    logo: images/logo.svg
    logo-href: https://ucospo.net
    target: _blank
    left:
      - href: index.qmd
        text: Home
      - href: status.qmd
        text: Updates

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



